### ISSUE TITLE
Is this package still under development?

### ISSUE THREAD

**Issue by awa5114** [LindaLinsefors/EinSumConv#1]
Hello,
I am very much interested in using this package for Einstein summation convention. However I have seen no help resources online such as tutorials or command reference to get started. Does anyone know whether this project still exists and if it can be used? 

Also when I tried to import in Python35  I got an error message

>>> import EinSumConv
Traceback (most recent call last):
  File "<pyshell#213>", line 1, in <module>
    import EinSumConv
  File "C:\Python35\lib\site-packages\EinSumConv\__init__.py", line 1, in <module>
    from delta import setDim, getDim, setIndexRange, getIndexRange, Delta, contractDeltas
ImportError: cannot import name 'setDim'

**Comment by LindaLinsefors** [comment]
Hi, sorry for the slow answer.
This is a project that I started long ago and never quite finished. It is written in Python 2.
